// Generato da scripts/scarica-foto.py + scripts/prepara-foto.py. Foto di proprietà dell'hotel (fotografa: Simona Bruno), non nel repo pubblico.
export type Foto = { src: string; sm: string; w: number; h: number; alt: string };
export const FOTO = {
  hotelNotte: { src: "/foto/web/hotelNotte.webp", sm: "/foto/web/hotelNotte-sm.webp", w: 1920, h: 1100, alt: "Facciata del Cosmo Hotel Palace illuminata al crepuscolo" },
  hall: { src: "/foto/web/hall.webp", sm: "/foto/web/hall-sm.webp", w: 1920, h: 1280, alt: "Hall con la grande scultura in legno d'ulivo e il lucernario" },
  hallAmpia: { src: "/foto/web/hallAmpia.webp", sm: "/foto/web/hallAmpia-sm.webp", w: 1920, h: 1280, alt: "La hall con scultura in legno d'ulivo e la porta d'ingresso a vetri" },
  ingresso: { src: "/foto/web/ingresso.webp", sm: "/foto/web/ingresso-sm.webp", w: 1920, h: 1329, alt: "Ingresso dell'hotel con la porta a vetri e il portico" },
  reception: { src: "/foto/web/reception.webp", sm: "/foto/web/reception-sm.webp", w: 1920, h: 1281, alt: "Reception e area d'ingresso con orchidee" },
  lounge: { src: "/foto/web/lounge.webp", sm: "/foto/web/lounge-sm.webp", w: 1920, h: 1280, alt: "Lounge Bar con orchidee e banco in pietra chiara" },
  loungeSala: { src: "/foto/web/loungeSala.webp", sm: "/foto/web/loungeSala-sm.webp", w: 1920, h: 1280, alt: "Corridoio del lounge con tende e orchidee" },
  bar: { src: "/foto/web/bar.webp", sm: "/foto/web/bar-sm.webp", w: 900, h: 600, alt: "Lounge Bar con tende leggere e salottini" },
  grill1: { src: "/foto/web/grill1.webp", sm: "/foto/web/grill1-sm.webp", w: 1920, h: 1280, alt: "Sala del ristorante Cosmo Grill con travi a vista" },
  grill2: { src: "/foto/web/grill2.webp", sm: "/foto/web/grill2-sm.webp", w: 1920, h: 1280, alt: "Tavoli del Cosmo Grill con grandi lampade paralume" },
  grill3: { src: "/foto/web/grill3.webp", sm: "/foto/web/grill3-sm.webp", w: 1920, h: 1281, alt: "Tavolo apparecchiato al Cosmo Grill" },
  grill4: { src: "/foto/web/grill4.webp", sm: "/foto/web/grill4-sm.webp", w: 1920, h: 1301, alt: "Sala del Cosmo Grill" },
  grill5: { src: "/foto/web/grill5.webp", sm: "/foto/web/grill5-sm.webp", w: 1920, h: 1280, alt: "Il ristorante Cosmo Grill con tavoli apparecchiati" },
  grill6: { src: "/foto/web/grill6.webp", sm: "/foto/web/grill6-sm.webp", w: 1920, h: 1281, alt: "Sala del Cosmo Grill con mensole e specchi" },
  grill7: { src: "/foto/web/grill7.webp", sm: "/foto/web/grill7-sm.webp", w: 1920, h: 1281, alt: "Tavoli del Cosmo Grill con lampade e vetrate" },
  classic1: { src: "/foto/web/classic1.webp", sm: "/foto/web/classic1-sm.webp", w: 1920, h: 1281, alt: "Classic Double Room con letto matrimoniale e scrivania" },
  classic2: { src: "/foto/web/classic2.webp", sm: "/foto/web/classic2-sm.webp", w: 1920, h: 1281, alt: "Classic Double Room con testiera imbottita e tre stampe" },
  classic3: { src: "/foto/web/classic3.webp", sm: "/foto/web/classic3-sm.webp", w: 1920, h: 1281, alt: "Classic Double Room con tavolo di lavoro" },
  classic4: { src: "/foto/web/classic4.webp", sm: "/foto/web/classic4-sm.webp", w: 1920, h: 1280, alt: "Classic Double Room, letto e comodino con abat-jour" },
  classic5: { src: "/foto/web/classic5.webp", sm: "/foto/web/classic5-sm.webp", w: 1920, h: 1281, alt: "Classic Double Room con letto, stampe e scrivania" },
  classicBagno: { src: "/foto/web/classicBagno.webp", sm: "/foto/web/classicBagno-sm.webp", w: 1920, h: 1281, alt: "Bagno con vasca e specchio con cornice dorata" },
  family1: { src: "/foto/web/family1.webp", sm: "/foto/web/family1-sm.webp", w: 1920, h: 1281, alt: "Family Room con camere comunicanti" },
  family2: { src: "/foto/web/family2.webp", sm: "/foto/web/family2-sm.webp", w: 1920, h: 1281, alt: "Family Room con letto singolo e scrivania" },
  family3: { src: "/foto/web/family3.webp", sm: "/foto/web/family3-sm.webp", w: 1920, h: 1268, alt: "Family Room con letto matrimoniale" },
  family4: { src: "/foto/web/family4.webp", sm: "/foto/web/family4-sm.webp", w: 1920, h: 1268, alt: "Letto matrimoniale di una Family Room" },
  family5: { src: "/foto/web/family5.webp", sm: "/foto/web/family5-sm.webp", w: 1920, h: 1281, alt: "Family Room: camera con scrivania e letto" },
  familyBagno: { src: "/foto/web/familyBagno.webp", sm: "/foto/web/familyBagno-sm.webp", w: 1920, h: 1281, alt: "Bagno con doccia e specchio" },
  suite1: { src: "/foto/web/suite1.webp", sm: "/foto/web/suite1-sm.webp", w: 1920, h: 1281, alt: "Suite con camera matrimoniale e zona soggiorno" },
  suite2: { src: "/foto/web/suite2.webp", sm: "/foto/web/suite2-sm.webp", w: 1920, h: 1280, alt: "Suite: soggiorno con scrivania e camera con letto" },
  suite3: { src: "/foto/web/suite3.webp", sm: "/foto/web/suite3-sm.webp", w: 1920, h: 1281, alt: "Suite con scrivania e porta verso la camera" },
  suite4: { src: "/foto/web/suite4.webp", sm: "/foto/web/suite4-sm.webp", w: 1920, h: 1280, alt: "Suite con letto, TV e mobile laccato rosso" },
  suite5: { src: "/foto/web/suite5.webp", sm: "/foto/web/suite5-sm.webp", w: 1920, h: 1280, alt: "Zona soggiorno della Suite con divano" },
  twin: { src: "/foto/web/twin.webp", sm: "/foto/web/twin-sm.webp", w: 1920, h: 1281, alt: "Camera con due letti singoli" },
  meeting1: { src: "/foto/web/meeting1.webp", sm: "/foto/web/meeting1-sm.webp", w: 1212, h: 870, alt: "Sala plenaria del Centro Congressi con sedie in platea" },
  meeting2: { src: "/foto/web/meeting2.webp", sm: "/foto/web/meeting2-sm.webp", w: 1103, h: 870, alt: "Sala Divinità allestita con sedie e tavolo di presidenza" },
  meeting3: { src: "/foto/web/meeting3.webp", sm: "/foto/web/meeting3-sm.webp", w: 1920, h: 1280, alt: "Sala meeting con tavoli a banchi di scuola" },
  meeting4: { src: "/foto/web/meeting4.webp", sm: "/foto/web/meeting4-sm.webp", w: 1920, h: 1281, alt: "Sala allestita a banchetto con tavoli rotondi" },
  meeting5: { src: "/foto/web/meeting5.webp", sm: "/foto/web/meeting5-sm.webp", w: 1920, h: 1291, alt: "Sala riunioni con tavoli a ferro di cavallo" },
  meeting6: { src: "/foto/web/meeting6.webp", sm: "/foto/web/meeting6-sm.webp", w: 1920, h: 1307, alt: "Sala riunioni con tavolo imperiale" },
  meeting7: { src: "/foto/web/meeting7.webp", sm: "/foto/web/meeting7-sm.webp", w: 1920, h: 1277, alt: "Plenaria con banchetto a tavoli rotondi" },
  meeting8: { src: "/foto/web/meeting8.webp", sm: "/foto/web/meeting8-sm.webp", w: 1920, h: 1281, alt: "Plenaria con platea e palco" },
  wellness1: { src: "/foto/web/wellness1.webp", sm: "/foto/web/wellness1-sm.webp", w: 1920, h: 1280, alt: "Area benessere con lettini e sauna sullo sfondo" },
  wellness2: { src: "/foto/web/wellness2.webp", sm: "/foto/web/wellness2-sm.webp", w: 1920, h: 1280, alt: "Area relax del centro benessere" },
  wellness3: { src: "/foto/web/wellness3.webp", sm: "/foto/web/wellness3-sm.webp", w: 1920, h: 1297, alt: "Sala fitness con tapis roulant e cyclette" },
  wellness4: { src: "/foto/web/wellness4.webp", sm: "/foto/web/wellness4-sm.webp", w: 1920, h: 1273, alt: "Area benessere con lettini in legno" },
  duomoMilano: { src: "/foto/web/duomoMilano.webp", sm: "/foto/web/duomoMilano-sm.webp", w: 1920, h: 1229, alt: "Il Duomo di Milano di notte" },
  corsoVittorioEmanuele: { src: "/foto/web/corsoVittorioEmanuele.webp", sm: "/foto/web/corsoVittorioEmanuele-sm.webp", w: 1920, h: 1280, alt: "Corso Vittorio Emanuele II con il Duomo sullo sfondo" },
  galleriaVE: { src: "/foto/web/galleriaVE.webp", sm: "/foto/web/galleriaVE-sm.webp", w: 1920, h: 1194, alt: "Galleria Vittorio Emanuele II" },
  cenacolo: { src: "/foto/web/cenacolo.webp", sm: "/foto/web/cenacolo-sm.webp", w: 1920, h: 1397, alt: "Santa Maria delle Grazie, sede del Cenacolo Vinciano" },
  reggiaMonza: { src: "/foto/web/reggiaMonza.webp", sm: "/foto/web/reggiaMonza-sm.webp", w: 1920, h: 1282, alt: "La Reggia di Monza e i suoi giardini" },
  parcoMonza: { src: "/foto/web/parcoMonza.webp", sm: "/foto/web/parcoMonza-sm.webp", w: 1916, h: 1280, alt: "Il Parco di Monza in autunno" },
  autodromo: { src: "/foto/web/autodromo.webp", sm: "/foto/web/autodromo-sm.webp", w: 1919, h: 1280, alt: "L'Autodromo Nazionale di Monza" },
  duomoMonza: { src: "/foto/web/duomoMonza.webp", sm: "/foto/web/duomoMonza-sm.webp", w: 1707, h: 1280, alt: "Il Duomo di Monza" },
  arengario: { src: "/foto/web/arengario.webp", sm: "/foto/web/arengario-sm.webp", w: 1919, h: 1280, alt: "L'Arengario di Monza" },
  leolandia: { src: "/foto/web/leolandia.webp", sm: "/foto/web/leolandia-sm.webp", w: 1920, h: 1280, alt: "Parco divertimenti" },
  villaCarlotta: { src: "/foto/web/villaCarlotta.webp", sm: "/foto/web/villaCarlotta-sm.webp", w: 1919, h: 1280, alt: "Villa Carlotta sul Lago di Como" },
  torri: { src: "/foto/web/torri.webp", sm: "/foto/web/torri-sm.webp", w: 1920, h: 1952, alt: "Cosmo Hotel Torri" },
  residence: { src: "/foto/web/residence.webp", sm: "/foto/web/residence-sm.webp", w: 1920, h: 1715, alt: "Cosmo Residence" },
  trivulzio: { src: "/foto/web/trivulzio.webp", sm: "/foto/web/trivulzio-sm.webp", w: 1640, h: 840, alt: "Villa Trivulzio vista dall'alto" },
} as const satisfies Record<string, Foto>;
export type FotoKey = keyof typeof FOTO;
